version: 2

models:
  # =========================================================================
  # CONSENSUS CHECK: Layer 3 - Cross-Source Validation
  # =========================================================================

  - name: consensus_check
    description: |
      Swiss Cheese Layer 3: Consensus Gate

      Cross-validates Frankfurter (ECB) vs ExchangeRate-API rates.
      Flags rates with >0.5% variance for manual review.

      This model only contains FLAGGED rates (anomalies).
      Empty table = all rates passed validation ✅
    columns:
      - name: target_currency
        description: Currency being validated
        tests:
          - not_null

      - name: variance_pct
        description: Percentage variance between sources
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0.005"  # Only flagged rates (>0.5%)

      - name: status
        description: Validation status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['FLAGGED']  # This table only contains flagged rates

      - name: severity
        description: Severity level for alerting
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['WARNING', 'CRITICAL']

  # =========================================================================
  # FACT TABLE: Layer 4 - Statistical Validation + Final Output
  # =========================================================================

  - name: fact_rates_validated
    description: |
      SINGLE SOURCE OF TRUTH for currency rates.

      Swiss Cheese Validation Complete:
      ✅ Layer 1 (dlt): Structural validation (schema, types)
      ✅ Layer 2 (dbt): Logical validation (constraints, ranges)
      ✅ Layer 3 (dbt): Consensus gate (cross-source validation)
      ✅ Layer 4 (dbt): Statistical checks (flash crash detection)

      Only includes rates that passed ALL validation layers.
      Ready for DynamoDB Hot Tier sync.
    columns:
      - name: extraction_id
        description: Unique extraction identifier
        tests:
          - not_null

      - name: rate_date
        description: Official rate date
        tests:
          - not_null

      - name: currency_pair
        description: Currency pair (e.g., EUR/USD)
        tests:
          - not_null

      - name: base_currency
        description: Base currency
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['EUR']  # Primary source is EUR-based

      - name: target_currency
        description: Target currency
        tests:
          - not_null

      - name: exchange_rate
        description: Validated exchange rate
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
          - dbt_utils.expression_is_true:
              expression: "< 1000000"

      - name: validation_status
        description: Final validation status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['VALIDATED']  # Only validated rates in this table

      - name: severity
        description: Severity (should be OK for all validated rates)
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['OK']

    # Table-level tests (Layer 4: Statistical Validation)
    tests:
      # Freshness check: Rates should be updated daily
      - dbt_utils.recency:
          datepart: day
          field: rate_date
          interval: 7  # Alert if no rates within 2 days

      # # Volume check: Should have consistent number of currency pairs
      # # Typical: 150+ currencies from ECB
      # - dbt_utils.expression_is_true:
      #     expression: "(SELECT COUNT(DISTINCT target_currency) FROM fact_rates_validated WHERE rate_date = (SELECT MAX(rate_date) FROM fact_rates_validated)) >= 100"
      #     config:
      #       severity: warn  # Warn if fewer than 100 currencies
