version: 2

models:
  # =========================================================================
  # CONSENSUS CHECK: Layer 3 - Cross-Source Validation
  # =========================================================================

  - name: consensus_check
    description: |
      Swiss Cheese Layer 3: Consensus Gate

      Cross-validates Frankfurter (ECB) vs ExchangeRate-API rates.
      Flags rates with >0.5% variance for manual review.

      This model only contains FLAGGED rates (anomalies).
      Empty table = all rates passed validation ✅
    columns:
      - name: target_currency
        description: Currency being validated
        tests:
          - not_null

      - name: variance_pct
        description: Percentage variance between sources
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0.005"  # Only flagged rates (>0.5%)

      - name: status
        description: Validation status
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['FLAGGED']  # This table only contains flagged rates

      - name: severity
        description: Severity level for alerting
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['WARNING', 'CRITICAL']

  # =========================================================================
  # FACT TABLE: Layer 4 - Statistical Validation + Final Output
  # =========================================================================

  - name: fact_rates_validated
    description: |
      SINGLE SOURCE OF TRUTH for currency rates.

      Swiss Cheese Validation Complete:
      ✅ Layer 1 (dlt): Structural validation (schema, types)
      ✅ Layer 2 (dbt): Logical validation (constraints, ranges)
      ✅ Layer 3 (dbt): Consensus gate (cross-source validation)
      ✅ Layer 4 (dbt): Statistical checks (flash crash detection)

      Only includes rates that passed ALL validation layers.
      Ready for DynamoDB Hot Tier sync.
    config:
      contract:
        enforced: true
    columns:
      - name: extraction_id
        description: Unique extraction identifier
        data_type: varchar
        constraints:
          - type: not_null
        tests:
          - not_null

      - name: rate_date
        description: Official rate date
        data_type: date
        constraints:
          - type: not_null
        tests:
          - not_null

      - name: currency_pair
        description: Currency pair (e.g., EUR/USD)
        data_type: varchar
        constraints:
          - type: not_null
        tests:
          - not_null

      - name: base_currency
        description: Base currency
        data_type: varchar
        constraints:
          - type: not_null
          - type: check
            expression: "base_currency = 'EUR'"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['EUR']  # Primary source is EUR-based

      - name: target_currency
        description: Target currency
        data_type: varchar
        constraints:
          - type: not_null
        tests:
          - not_null

      - name: exchange_rate
        description: Validated exchange rate
        data_type: double
        constraints:
          - type: not_null
          - type: check
            expression: "exchange_rate > 0 AND exchange_rate < 1000000"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
          - dbt_utils.expression_is_true:
              expression: "< 1000000"

      - name: validation_status
        description: Final validation status
        data_type: varchar
        constraints:
          - type: not_null
          - type: check
            expression: "validation_status = 'VALIDATED'"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['VALIDATED']  # Only validated rates in this table

      - name: severity
        description: Severity (should be OK for all validated rates)
        data_type: varchar
        constraints:
          - type: not_null
          - type: check
            expression: "severity = 'OK'"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['OK']

      - name: extraction_timestamp
        description: When the data was extracted
        data_type: timestamp
        constraints:
          - type: not_null

      - name: source
        description: Data source identifier
        data_type: varchar
        constraints:
          - type: not_null

      - name: source_tier
        description: Data source tier (primary/secondary)
        data_type: varchar

      - name: inverse_rate
        description: Inverse exchange rate (1/exchange_rate)
        data_type: double
        constraints:
          - type: not_null
          - type: check
            expression: "inverse_rate > 0"

      - name: consensus_variance
        description: Variance from consensus (0.0 if validated)
        data_type: double
        constraints:
          - type: not_null
          - type: check
            expression: "consensus_variance = 0.0"

      - name: dbt_loaded_at
        description: Timestamp when dbt loaded this record
        data_type: timestamp with time zone

      - name: model_name
        description: dbt model name
        data_type: varchar

    # Table-level tests (Layer 4: Statistical Validation)
    tests:
      # Freshness check: Rates should be updated daily
      - dbt_utils.recency:
          datepart: day
          field: rate_date
          interval: 7  # Alert if no rates within 7 days
          severity: warn  # Don't fail pipeline on stale data, just warn

